import type { Metadata } from "next";
import Link from "next/link";

import { APP_NAME } from "@/lib/constants/brand";
import { SiteFooter } from "@/components/site-footer";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `Privacy Policy for ${APP_NAME} – how we collect, use, and protect your data.`,
  alternates: {
    canonical: "/privacy",
  },
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[linear-gradient(to_bottom_right,var(--background),var(--background),oklch(0.98_0.01_175/0.3))] p-4 sm:p-6 relative overflow-hidden">
      <div className="absolute top-[-10%] left-[-10%] w-[50%] aspect-square bg-primary/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-[-15%] right-[-10%] w-[45%] aspect-square bg-primary/10 rounded-full blur-3xl pointer-events-none" />

      <div className="relative z-10 max-w-3xl mx-auto">
        <header className="mb-8">
          <Link
            href="/login"
            className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground mb-6"
          >
            ← Back to sign in
          </Link>
          <h1 className="text-3xl font-bold text-foreground">
            Privacy Policy
          </h1>
          <p className="text-muted-foreground mt-2">
            Last updated: March 2026. This policy describes how {APP_NAME}{" "}
            handles your information.
          </p>
        </header>

        <article className="p-4 sm:p-6 space-y-8 text-foreground">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Who We Are</h2>
            <p className="text-muted-foreground leading-relaxed">
              {APP_NAME} (&quot;we&quot;, &quot;our&quot;) operates a ride-sharing platform that
              allows users to find or offer rides. This Privacy Policy explains
              what data we collect, how we use it, and your rights regarding that
              data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Information We Collect</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">
              We collect information you provide and information generated by
              your use of the Service:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>
                <strong className="text-foreground">Account and profile:</strong>{" "}
                When you sign in (e.g. via Google), we receive and store
                identifiers (such as name, email, and profile picture) and may
                store additional details you add (e.g. phone number, bio).
              </li>
              <li>
                <strong className="text-foreground">Rides and bookings:</strong>{" "}
                Ride details (routes, times, price, seats), bookings, pickup and
                drop notes, and related communications.
              </li>
              <li>
                <strong className="text-foreground">Usage and device:</strong>{" "}
                Logs, IP address, browser/device type, and how you use the app
                (e.g. searches, pages visited) for operation and security.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. How We Use Your Information</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">
              We use the information we collect to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Provide, maintain, and improve the Service.</li>
              <li>Match riders with drivers and manage bookings and messages.</li>
              <li>Display your profile and ride history to other users as needed for the Service (e.g. driver to rider, rider to driver).</li>
              <li>Send service-related notifications (e.g. booking confirmations, ride updates).</li>
              <li>Detect and prevent fraud, abuse, and security issues.</li>
              <li>Comply with legal obligations and enforce our Terms and Conditions.</li>
              <li>Analyse usage in an aggregated way to improve the product.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Sharing of Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may share your information with: (a) other users as necessary
              for the Service (e.g. your name and contact details with your
              driver or riders); (b) service providers that help us operate the
              platform (hosting, analytics, auth), under strict confidentiality;
              (c) law enforcement or authorities when required by law or to
              protect rights and safety; (d) in connection with a merger, sale,
              or restructuring, with notice where required. We do not sell your
              personal data to third parties for their marketing.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Data Retention and Security</h2>
            <p className="text-muted-foreground leading-relaxed">
              We retain your data for as long as your account is active and as
              needed to provide the Service, resolve disputes, and comply with
              legal obligations. We implement appropriate technical and
              organisational measures to protect your data; no system is
              completely secure, and you use the Service at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Your Rights</h2>
            <p className="text-muted-foreground leading-relaxed">
              Depending on your location, you may have the right to access,
              correct, or delete your personal data, or to object to or restrict
              certain processing. You can update profile information in the app.
              For other requests or questions about this policy, contact us
              through the channels provided. You may also have the right to
              lodge a complaint with a data protection authority.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Third-Party Services</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Service uses third-party services (e.g. authentication
              providers like Google). Their use of your data is governed by
              their own privacy policies. We encourage you to review those
              policies when you sign in or use linked features (e.g. sharing a
              ride link via WhatsApp).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Changes to This Policy</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update this Privacy Policy from time to time. We will post
              the updated version with a new &quot;Last updated&quot; date. Your continued
              use of the Service after changes constitutes acceptance of the
              updated policy. For material changes, we may provide additional
              notice where required by law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              For privacy-related questions or to exercise your rights, please
              contact us through the contact options provided in the app or on
              our website.
            </p>
          </section>
        </article>
      </div>
      <SiteFooter />
    </div>
  );
}
